const request = require('supertest')
const app = require('../app')
describe('Currency-list EndPoint Check', () => {
    it('currency-list end point check', async() => {
        const res = await request(app).get("/currency-list")
        expect(res.statusCode).toEqual(200)
        expect(res.body.currency_list).toEqual({
            "ATS": "Austrian shilling",
            "AUD": "Australian dollar",
            "BEF": "Belgium franc",
            "BRL": "Brazil real",
            "CAD": "Canadian dollar",
            "CHF": "Swiss francs",
            "CNY": "Chinese yuan renminbi",
            "CYP": "Cyprus pound",
            "CZK": "Czech koruna",
            "DEM": "German mark",
            "DKK": "Danish krone",
            "EEK": "Estonian kroon",
            "ESP": "Spanish pesetas",
            "EUR": "Euroland euro",
            "FIM": "Finnish marka",
            "FRF": "French franc",
            "GBP": "pound sterling",
            "GRD": "Greek drachmer",
            "HKD": "Hong Kong dollar",
            "HUF": "Hungarian forints",
            "IDR": "Indonesian rupiah",
            "IEP": "Irish pund",
            "INR": "Indian rupee",
            "ISK": "Icelandic kronor",
            "ITL": "Italian lire",
            "JPY": "Japanese yen",
            "KRW": "South Korean won",
            "KWD": "Kuwaiti dinar",
            "LTL": "Lithuanian litas",
            "LVL": "Latvian lat",
            "MAD": "Moroccan dirham (MAD)",
            "MXN": "Mexican nuevo peso",
            "MYR": "Malaysian ringgit",
            "NLG": "Dutch guilder",
            "NOK": "Norwegian krone",
            "NZD": "New Zealand dollar",
            "PLN": "Polish zloty (PLN)",
            "PTE": "Portuguese escudo",
            "RUB": "Russian rouble",
            "SAR": "Saudi Arabian riyal",
            "SEK": "Swedish krona",
            "SGD": "Singapore dollar",
            "SIT": "Slovenian tolar",
            "SKK": "Slovakian koruna",
            "THB": "Thai baht",
            "TRL": "Turkish lira",
            "TRY": "Turkish new lira",
            "USD": "US dollar",
            "ZAR": "South African rand"
        })
    })
        it('python_app currency-list end point check', async() => {
            const res = await request("0.0.0.0:5002").get("/currency-list")
            expect(res.statusCode).toEqual(200)
            expect(res.body.currency_list).toEqual({
                "ATS": "Austrian shilling",
                "AUD": "Australian dollar",
                "BEF": "Belgium franc",
                "BRL": "Brazil real",
                "CAD": "Canadian dollar",
                "CHF": "Swiss francs",
                "CNY": "Chinese yuan renminbi",
                "CYP": "Cyprus pound",
                "CZK": "Czech koruna",
                "DEM": "German mark",
                "DKK": "Danish krone",
                "EEK": "Estonian kroon",
                "ESP": "Spanish pesetas",
                "EUR": "Euroland euro",
                "FIM": "Finnish marka",
                "FRF": "French franc",
                "GBP": "pound sterling",
                "GRD": "Greek drachmer",
                "HKD": "Hong Kong dollar",
                "HUF": "Hungarian forints",
                "IDR": "Indonesian rupiah",
                "IEP": "Irish pund",
                "INR": "Indian rupee",
                "ISK": "Icelandic kronor",
                "ITL": "Italian lire",
                "JPY": "Japanese yen",
                "KRW": "South Korean won",
                "KWD": "Kuwaiti dinar",
                "LTL": "Lithuanian litas",
                "LVL": "Latvian lat",
                "MAD": "Moroccan dirham (MAD)",
                "MXN": "Mexican nuevo peso",
                "MYR": "Malaysian ringgit",
                "NLG": "Dutch guilder",
                "NOK": "Norwegian krone",
                "NZD": "New Zealand dollar",
                "PLN": "Polish zloty (PLN)",
                "PTE": "Portuguese escudo",
                "RUB": "Russian rouble",
                "SAR": "Saudi Arabian riyal",
                "SEK": "Swedish krona",
                "SGD": "Singapore dollar",
                "SIT": "Slovenian tolar",
                "SKK": "Slovakian koruna",
                "THB": "Thai baht",
                "TRL": "Turkish lira",
                "TRY": "Turkish new lira",
                "USD": "US dollar",
                "ZAR": "South African rand"
            })
    })
  })