 
name: Continuous Deployment

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      run: |
        echo PHP_HOSTNAME = calculate_backend > .env
        echo PHP_PORT = 8000 >> .env
        echo PYTHON_HOSTNAME = exchange_backend >> .env
        echo PYTHON_PORT = 5000 >> .env
      working-directory: ./nodejs_app
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }}
        -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker Image(python)
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: mucahitfindik/exchange_backend
        dockerfile: ./python_app/Dockerfile
        directory: python_app
        tags: v1
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker Image (php)
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: mucahitfindik/calculate_backend
        dockerfile: ./php_app/Dockerfile
        directory: php_app
        tags: v1
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker Image (nodejs)
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: mucahitfindik/center_backend
        dockerfile: ./nodejs_app/Dockerfile
        directory: nodejs_app
        tags: v1
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
